---
- name: Simple test playbook
  hosts: all
  tasks:
    - name: Display a message
      debug:
        msg: "Hello from Ansible playbook via Jenkins!"

    - name: Check system information
      command: uname -a
      register: uname_result

    - name: Show system info
      debug:
        var: uname_result.stdout

    - name: Run neofetch to display system info
      command: neofetch --stdout
      register: neofetch_result
      ignore_errors: yes  # In case neofetch is not installed

    - name: Show neofetch output
      debug:
        var: neofetch_result.stdout
      when: neofetch_result is succeeded

    - name: Warning if neofetch not installed
      debug:
        msg: "neofetch is not installed on the system"
      when: neofetch_result is failed
