---
- name: Simple test playbook
  hosts: all
  tasks:
    - name: Display a message
      debug:
        msg: "Hello from Ansible playbook via Jenkins!"

    - name: Check system information
      command: uname -a
      register: uname_result

    - name: Show system info
      debug:
        var: uname_result.stdout
